// resources/js/Pages/Dashboard/Apps.svelte
<script>
    import Dashboard from "../../Components/Layouts/Dashboard.svelte"
</script>

<Dashboard id="apps">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
        <h1 class="text-2xl font-semibold text-gray-900">Apps</h1>
    </div>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
        <slot />
    </div>
</Dashboard>

// resources/js/Pages/Apps.jsx
import AppCard from '@/Components/AppCard';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head } from '@inertiajs/react';

export default function Apps(props) {
    return (
        <AuthenticatedLayout
            auth={props.auth}
            errors={props.errors}
            header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Apps</h2>}
        >
            <Head title="Apps" />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="grid grid-cols-1 gap-4">
                        {props.apps.map(app => <AppCard key={app.id} app={app} />)}
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
